### PR TITLE
Fix shared library loading without dev packages on Linux

### PR DESCRIPTION
**Pull request by fffonion**
This PR also adds tests thorugh GHA.

### CODE REVIEW

**Comment by hamishforbes** [comment]
Nice, happy to merge this but, is it neccessary to build all of openresty to run the tests? Could we just use a pre-built openresty image instead?

Just seems like something fairly complicated to maintain and potentially fragile

**Comment by fffonion** [comment]
Ah yes you are right, I can just use docker. Let me try that.

**Comment by fffonion** [comment]
Thank you @hamishforbes , would you release a new version to include this fix?

**Comment by hamishforbes** [comment]
Yep, had to re-acquaint myself with opm/luarocks as it's been a while! Released as 0.6 now

**Pull request merged**
