### PR TITLE
add some error handling

### PR DESCRIPTION
**Pull request by sjnam**
Constant Z_NEED_DICT has positive value but it should be considered an error.

### CODE REVIEW

**Comment by hamishforbes** [comment]
Hi, thanks for catching that!

I don't fully understand why you're converting `Z_NEED_DICT` to `Z_DATA_ERROR` and removing the `< z_OK` check?  
Does it not make more sense to simply change line 184 to `if err < Z_OK or err == Z_NEED_DICT then`.

Your change ignores a number of error returns, but does seem to work...

**Comment by hamishforbes** [comment]
Nevermind, found this on the zlib 

> Note that a Z_BUF_ERROR is not fatal--another call to deflate() or inflate() can be made with more input or output space.

http://www.zlib.net/zlib_faq.html#faq05

Made some tweaks, can you confirm that resolves your issue?

**Comment by sjnam** [comment]
Good!
Thanks for providing very useful module lua-ffi-zlib.

**Comment by hamishforbes** [comment]
Hey, there looks to be a bug in that change after all.
There are some interesting subtleties in error handling when inflating vs deflating as explained here: http://zlib.net/zlib_how.html

I've separated those 2 functions and modified the logic to match the reference implementation [here](http://zlib.net/zpipe.c)

Can you check v0.3 still works for you.

**Pull request merged**
